export const theme = {
  colors: {
    black: 'black',
    white: 'white',
    green: 'green',
    red: 'red',
    ivory: '#EEEDE7',
    boxColor: '#E7D2CC',
    lightGray: '#e2e8f0;',
    lightBlue: '#EBF8FF',
    headerColor: '#3182CE',
    ligtherBlue: '#2B6CB0',
    darkBlue: '#1A365D',
    blue100: '#BEE3F8',
    blue200: '#90CDF4',
    blue50: '#EBF8FF',
  },
  space: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 'auto'],
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '12px',
    s: '14px',
    m: '16px',
    sm: '20px',
    l: '32px',
    ml: '42px',
    x: '54px',
    xl: '64px',
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
    bold: '3px solid',
  },
  radii: {
    none: '0',
    normal: '4px',
    superRound: '8px',
    round: '50%',
  },
};
